name: CI

on:
  push:
    branches: [ main ]
    paths:
    - .github/workflows/ci.yml
    - Instances/**
    - Instances.Tests/**
  pull_request:
    branches: [ main ]
    paths:
    - .github/workflows/ci.yml
    - Instances/**
    - Instances.Tests/**


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Run unit tests and collect coverage
      run: dotnet test --collect "XPlat Code Coverage" --logger GitHubActions --verbosity normal

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: Instances.Tests/TestResults
        fail_ci_if_error: true
